// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Gridonator = (function() {
    function Gridonator(__container, __containees, __max_width) {
      this.__container = __container;
      this.__containees = __containees;
      this.__max_width = __max_width;
      this.update = __bind(this.update, this);
    }

    Gridonator.prototype.update = function() {
      var columns, el, width, _i, _len, _ref, _results;

      columns = Math.floor(this.__container.clientWidth / this.__containees[0].clientWidth);
      if (this.__container.clientWidth / columns > this.__max_width) {
        columns++;
      }
      width = Math.floor(this.__container.clientWidth / columns);
      _ref = this.__containees;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        el = _ref[_i];
        _results.push(el.style.width = "" + width + "px");
      }
      return _results;
    };

    return Gridonator;

  })();

}).call(this);
